---
locale: 'en'
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
backend:
  # See https://www.netlifycms.org/docs/authentication-backends/#github-backend
  name: github
  repo: dcycle/dcycle-site-2025
  branch: master
  base_url: https://auth.static.dcycle.com
  auth_endpoint: auth/github/alberto56
media_folder: 'hugo/static/media'
public_folder: "/media"
collections:
  - name: 'posts'
    create: true
    label: 'Posts'
    folder: 'hugo/content/posts'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
